source 'https://rubygems.org'
# source 'https://rails-assets.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'haml-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'upjs-rails', path: '..'
gem 'bower-rails'

# Jasmine spec runner won't boot with a more modern version of sprockets.
# It crashes with an "asset not precompiled" error.
gem 'tilt', '=1.4.1'
gem 'sprockets-rails', '=2.2.4'
gem 'sprockets', '=2.12.3'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'jasmine-rails'
end

group :test do
  gem 'rspec-rails'
end
