source 'https://rubygems.org'
# source 'https://rails-assets.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'haml-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'unpoly-rails', path: '..'
gem 'bower-rails'
gem 'bootstrap-sass', '~> 3.3'
gem 'rake', '< 11'

gem 'tilt', '=1.4.1'
gem 'sprockets-rails', '~> 3.2.1'
gem 'sprockets', '~> 3.7.2'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'jasmine-rails', git: 'https://github.com/triskweline/jasmine-rails.git', branch: 'hk/jasmine3'
  gem 'jasmine-core', '<3'
end

group :test do
  gem 'rspec-rails'
end
